Cross Validation --

Evaluating Model Performance

It helps us in finding which model to apply on which dataset.

We can train the model by three types --

1. Train 100% data and test from this data but it has a problem that the model has already seen the testing data while training because the data is same in both so it is less efficient.

2. Train_test_split method in this method we can train 70% data and test by 30% it has some more accuracy but there is a problem in this method that if the data is not as same type as training data then its accuracy decreases. also in this method on each execution the training dataset changes so score also changes.

3. K-fold cross validation is a most used type of cross validation in this method we make groups of data which is called folds for example if there are 100 samples of data than we devide this samples in 5 folds of 20 samples and then we test by 1 fold and train by remaining 4 folds. then we test by 2 fold and train  by remaining folds and so on upto test by 5 fold and train  by upper 4 folds.


After this we take individual scores of all the groups and average it and get average score.
average score = score 1 + score 2 + score 3 + score 4 + score 5.

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
from sklearn.datasets import load_digits
digits = load_digits()

In [11]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

Deviding the data --

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

Now checking score by Logistic Regression --

In [13]:
le = LogisticRegression()
le.fit(x_train,y_train)


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
## BY LOGISTIC REGRESSION---
model.score(x_test,y_test)

NameError: name 'model' is not defined

In [ ]:
##  BY SVM --
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9549248747913188

In [ ]:
## By Random Forest --
model = RandomForestClassifier(n_estimators=40)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9777777777777777

Now Using K-fold method ---

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)  ## spliting data into 3 folds(groups)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

Example dataset--

In [ ]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In this the data is being shuffled in training first 2 groups are trained and 1 is tested then last 2 trained and 1 tested then first and last trained and middle tested

Now using K fold on digits dataset--

In [ ]:
for train_index,test_index in kf.split(digits.data):
  x_train,x_test,y_train,y_test= digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
model.fit(x_train,y_train)



0.9549248747913188

In [ ]:
model.score(x_test,y_test)


0.9165275459098498

In [ ]:
le.score(x_test,y_test)


0.9148580968280468

In [ ]:
svm.score(x_test,y_test)

0.9549248747913188

Now importing cross_val_score to check the score--  we have to use only this cross_val_score to compare the scores no need to do other all process.

In [ ]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.925     , 0.89166667, 0.9637883 , 0.95821727, 0.93036212])

Now Importing Another Data set --

For comparing which Algorithm is most accurate for this dataset and which algorithm to use for this dataset model training. 

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

Now Using cross_val_scores --

In [ ]:
from sklearn.model_selection import cross_val_score

Using Logistic Regression--

In [18]:
l_scores = cross_val_score(LogisticRegression(),iris.data,iris.target)
l_scores

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [19]:
import numpy as np

In [20]:
np.average(l_scores)

0.9733333333333334

Using Decision Tree --

In [22]:
from sklearn.tree import DecisionTreeClassifier


In [24]:
d_scores = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_scores
np.average(d_scores)

0.9600000000000002

Using Support Vector Machine (SVM)--

In [27]:
s_scores = cross_val_score(SVC(),iris.data,iris.target)
np.average(s_scores)

0.9666666666666666

Using Random Forest --

In [28]:
r_scores = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
np.average(r_scores)

0.96

HENCE THE LOGISTIC REGRESSION IS GIVING THE HIGHEST ACCURACY IN MODEL , SO WE WILL USE LOGISTIC REGRESSION.