WORKS ON LINEAR/CONTINUOUS DATA--

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
df = pd.read_csv('homeprices.csv')
df
area	price
0	2600	550000
1	3000	565000
2	3200	610000
3	3600	680000
4	4000	725000
%matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')
<matplotlib.collections.PathCollection at 0x25c8eb78d68>

new_df = df.drop('price',axis='columns')
new_df
area
0	2600
1	3000
2	3200
3	3600
4	4000
price = df.price
price
0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64
# Create linear regression object
reg = linear_model.LinearRegression()
reg.fit(new_df,price)
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)
(1) Predict price of a home with area = 3300 sqr ft

reg.predict([[3300]])
array([628715.75342466])
reg.coef_
array([135.78767123])
reg.intercept_
180616.43835616432
Y = m * X + b (m is coefficient and b is intercept)

3300*135.78767123 + 180616.43835616432
628715.7534151643
(1) Predict price of a home with area = 5000 sqr ft

reg.predict([[5000]])
array([859554.79452055])